name = "cloudflare-pages-spa-template"
compatibility_date = "2024-07-01"
pages_build_output_dir = "./dist"
# compatibility_flags = ["nodejs_compat"]

#[[kv_namespaces]]
#binding = "KV"
#id = "<NAMESPACE_ID>"
